//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SAK_2016.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class dbSakQueries : global::System.Configuration.ApplicationSettingsBase {
        
        private static dbSakQueries defaultInstance = ((dbSakQueries)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new dbSakQueries())));
        
        public static dbSakQueries Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("db_sak")]
        public string dbName {
            get {
                return ((string)(this["dbName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Cables.id, Cables.name, Cables.struct_name,  Cables.notes, Cables.code_okp" +
            ", Cables.code_kch, documents.short_name as document_name FROM Cables LEFT JOIN d" +
            "ocuments ON (Cables.document_id = documents.id)")]
        public string selectCables {
            get {
                return ((string)(this["selectCables"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Cables.id, Cables.name, Cables.struct_name,  Cables.notes, Cables.code_okp" +
            ", Cables.code_kch, documents.short_name as document_name FROM Cables LEFT JOIN d" +
            "ocuments ON (Cables.document_id = documents.id)")]
        public string selectCableStructures {
            get {
                return ((string)(this["selectCableStructures"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Distinct Cables.name from Cables ORDER BY Cables.name ASC")]
        public string selectCableMarks {
            get {
                return ((string)(this["selectCableMarks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT lead_materials.id, lead_materials.name from lead_materials ORDER BY lead_m" +
            "aterials.id ASC")]
        public string selectLeadMaterials {
            get {
                return ((string)(this["selectLeadMaterials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT DISTINCT cable_structures.lead_diameter FROM cable_structures ORDER BY cab" +
            "le_structures.lead_diameter ASC")]
        public string selectLeadDiameters {
            get {
                return ((string)(this["selectLeadDiameters"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT isolation_materials.id, isolation_materials.name from isolation_materials " +
            "ORDER BY isolation_materials.id ASC")]
        public string selectIsolationMaterials {
            get {
                return ((string)(this["selectIsolationMaterials"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string selectUsers {
            get {
                return ((string)(this["selectUsers"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Distinct documents.id, documents.short_name, documents.full_name  FROM doc" +
            "uments ")]
        public string selectDocuments {
            get {
                return ((string)(this["selectDocuments"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM dr_formuls ORDER BY dr_formuls.id ASC")]
        public string selectDrFormuls {
            get {
                return ((string)(this["selectDrFormuls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM dr_bringing_formuls ORDER BY dr_bringing_formuls.id ASC")]
        public string selectDrBringingFormuls {
            get {
                return ((string)(this["selectDrBringingFormuls"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT Distinct cable_structures.wave_resistance from cable_structures ORDER BY c" +
            "able_structures.wave_resistance ASC")]
        public string selectWaveResistance {
            get {
                return ((string)(this["selectWaveResistance"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * from cable_structure_types ORDER BY cable_structure_types.id ASC")]
        public string selectCableStructureTypes {
            get {
                return ((string)(this["selectCableStructureTypes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT * FROM baraban_types ORDER BY baraban_types.name ASC")]
        public string selectBarabanTypes {
            get {
                return ((string)(this["selectBarabanTypes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("INSERT INTO baraban_types (baraban_types.name, baraban_types.weight) VALUES (\"{0}" +
            "\", {1})")]
        public string insertBarabanType {
            get {
                return ((string)(this["insertBarabanType"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"SELECT cable_structures.id, cable_structures.structure_type_id, cable_structures.fact_amount, cable_structures.nominal_amount, cable_structures.lead_material_id, cable_structures.isolation_material_id, lead_materials.name as lead_material_name, lead_materials.tkc_1 as lead_material_tkc, isolation_materials.name as isolation_material_name, cable_structures.lead_diameter, cable_structures.wave_resistance, cable_structures.u_lead_lead, cable_structures.u_lead_shield, cable_structures.test_group_work_capacity, cable_structures.dr_formula_id, dr_formuls.formula as dr_formula_formula, cable_structures.dr_bringing_formula_id, dr_bringing_formuls.formula as dr_bringing_formula_formula FROM cable_structures LEFT JOIN lead_materials ON (cable_structures.lead_material_id = lead_materials.id) LEFT JOIN isolation_materials ON (cable_structures.isolation_material_id = isolation_materials.id) LEFT JOIN dr_formuls ON (cable_structures.dr_formula_id = dr_formuls.id) LEFT JOIN dr_bringing_formuls ON (cable_structures.dr_bringing_formula_id = dr_bringing_formuls.id)  WHERE cable_structures.cable_id IN ({0})
")]
        public string selectCableStructuresListByCableId {
            get {
                return ((string)(this["selectCableStructuresListByCableId"]));
            }
        }
    }
}
